### ISSUE TITLE
Etusivun päivämääräformaatti

### ISSUE THREAD

**Issue by PetteriAimonen** [HacklabJKL/site#14]
Etusivun blogipostausten päivämäärät näkyvät muodossa "(kuukausi/päivä/vuosi)" eli "(5/8/2022)", joka ei ole suomessa kovin yleinen muoto. Joko päivä.kuukausi.vuosi tai vuosi-kuukausi-päivä olisi mielestäni parempi.

**Comment by jasalt** [comment]
Hyvä huomio, vakiona muoto on huono, vaihdoin nyt vuosi-kuukausi-päivä -muotoon näin:


Sivun muokkaus aktivoidaan etusivulla admin-käyttöoikeuksin kirjautuneena "Muokkaa sivua"-painikkeesta yläpalkista.

Blogi-osion sisällön luo [display-posts] -shortcode joka on lisäosana asennettu templatointifunktio. Shortcodejen käyttö tällaiseen käymässä legacy-tekniikaksi uuden blokkieditorin tukiessa Query Loop -blokin kautta vastaavaa toimintaa, mutta sivustolla on ongelma Rest-API:n kanssa joka estää Query Loop -blokin käytön.

Hakukone löytää vastauksen "display posts shortcode date format" sanoilla kyseisen shortcode parametrien dokumentaatiosivulta https://displayposts.com/docs/parameters/, ja vaihtoehtoisena tapana kytkeä date-format seuraamaan WP:n globaalia date-format asetusta https://displayposts.com/2019/09/11/use-the-wordpress-date-format/.

Laitoin parametriksi nyt date_format="Y-m-d", jota voi muuttaa https://wordpress.org/support/article/formatting-date-and-time/ mukaan.
