### ISSUE TITLE
Wikisivujen editointi ei toimi, jos sivu on tehty lohkoeditorilla

### ISSUE THREAD

**Issue by zouppen** [HacklabJKL/site#15]
Toistaminen:

1. Avaa wikisivu, joka tehty lohkoeditorilla, esim. https://jyväskylä.hacklab.fi/wikipage/sahkot/
2. Paina "Edit article"
3. Tulee virheilmoitus *The editor has encountered an unexpected error.*

Video ongelmasta: https://user-images.githubusercontent.com/978376/188848712-1ac1e899-0a0a-4529-b862-1da831b3307b.mp4

**Comment by PetteriAimonen** [comment]
Workaroundina voi urlin perään lisätä `&classic-editor`, esim. https://jyväskylä.hacklab.fi/wp-admin/post.php?post=2032&action=edit&classic-editor

**Comment by PetteriAimonen** [comment]
Omasta profiilista pystyy asettamaan oletuseditoriksi classic editorin, sillä ainakin itsellä toimii.

**Comment by jasalt** [comment]
Lähti toimimaan kun päivitin WP 6.0 ja poistin Gutenberg beta-lisäosan päältä. Pitäis olla astetta stablempi ilman sitä jatkossa, taisi jäädä vähän turhaan päälle viime layout-päivittelyjen jälkeen.
